<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-2LECONJ" failures="19" tests="253" name="api.TestRunner.TestRunner" time="132.639" errors="0" timestamp="2024-04-02T12:22:50 EDT" skipped="0">
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.410"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.220"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.253"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.207"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.341">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.StepDefinition.UserControllerStepDef.admin_receives_with_response_body_for_updated_user(UserControllerStepDef.java:572)
at ✽.Admin receives "400" with response body for Updated user.(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/05UserModule_PUT.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.334"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.266">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.StepDefinition.UserControllerStepDef.admin_receives_with_response_body_for_updated_user(UserControllerStepDef.java:572)
at ✽.Admin receives "400" with response body for Updated user.(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/05UserModule_PUT.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.417"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.256"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.283"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.278"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.418"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.287"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="4.172"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.233"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.319">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.StepDefinition.UserControllerStepDef.admin_receives_with_response_body_for_updated_user(UserControllerStepDef.java:572)
at ✽.Admin receives "400" with response body for Updated user.(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/05UserModule_PUT.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.219"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.394"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.430"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.207"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.265"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.345"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.279"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.317"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.283"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.288"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.203"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.357"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.276"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="5.090"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.216"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.240">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.StepDefinition.UserControllerStepDef.admin_receives_with_response_body_for_updated_user(UserControllerStepDef.java:572)
at ✽.Admin receives "400" with response body for Updated user.(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/05UserModule_PUT.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.700">
    <failure message="expected [400] but found [201]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [201]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.StepDefinition.UserControllerStepDef.admin_receives_with_response_body(UserControllerStepDef.java:105)
at ✽.Admin receives "400" with response body.(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/04UserModule_POST_GET.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.285"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.204"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.291"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.411"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.285"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.205"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.335"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.249"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.418"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.411"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.225"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.223"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.271"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.289"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.286"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.286"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.246"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="4.025"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.222"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.282"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.285"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.235"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="5.767"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.251"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.202"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.397"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.220"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.719">
    <failure message="expected [400] but found [201]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [201]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.StepDefinition.UserControllerStepDef.admin_receives_with_response_body(UserControllerStepDef.java:105)
at ✽.Admin receives "400" with response body.(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/04UserModule_POST_GET.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.223"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.221"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.295"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.281"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.206"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.205"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.283"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.272"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.445"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.330"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.219"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.281"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.253"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.267"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.431"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.334"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.221"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.256"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.415"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.258"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.205"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="4.119"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.265"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.314"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.386"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.268"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.383"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.328"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.277"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.209"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.276"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.394">
    <failure message="expected [] but found [www.linkedin.com]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [] but found [www.linkedin.com]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:644)
at api.StepDefinition.UserControllerStepDef.admin_receives_with_response_body_for_updated_user(UserControllerStepDef.java:581)
at ✽.Admin receives "200" with response body for Updated user.(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/05UserModule_PUT.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.223"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.288"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="4.075"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.285"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.285"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.301"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="5.002"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.320"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.253"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.221"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.253"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.215"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.280"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.210"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.258"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.330"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.253"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.257"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.282"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.224"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.265"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.223"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.236"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.196"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.272"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.227"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.267"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.247">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.StepDefinition.UserControllerStepDef.admin_receives_with_response_body_for_updated_user(UserControllerStepDef.java:572)
at ✽.Admin receives "400" with response body for Updated user.(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/05UserModule_PUT.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.210"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.625"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.267"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="4.037"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.236"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="4.474"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.318"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.218"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.198"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.374"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="1.328"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.204"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.319"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.236"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.239"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.266"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.235">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.StepDefinition.UserControllerStepDef.admin_receives_a_with_a_response_message(UserControllerStepDef.java:730)
at ✽.Admin receives a "400" with a response message(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/05UserModule_PUT.feature:159)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.306"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.312"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="4.056"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.259"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.277">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.StepDefinition.UserControllerStepDef.admin_receives_with_response_body_for_updated_user(UserControllerStepDef.java:572)
at ✽.Admin receives "400" with response body for Updated user.(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/05UserModule_PUT.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.224"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.300"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.272"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.269"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.319">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.StepDefinition.UserControllerStepDef.admin_receives_with_response_body_for_updated_user(UserControllerStepDef.java:572)
at ✽.Admin receives "400" with response body for Updated user.(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/05UserModule_PUT.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.285">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.StepDefinition.UserControllerStepDef.admin_receives_with_response_body_for_updated_user(UserControllerStepDef.java:572)
at ✽.Admin receives "400" with response body for Updated user.(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/05UserModule_PUT.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.349"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.237"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.293"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.397"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.357"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.269"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.254"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.473">
    <failure message="expected [404] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.StepDefinition.BatchStepDef.admin_receives_Not_Found_Status_with_message_and_boolean_success_details(BatchStepDef.java:562)
at ✽.Admin receives 404 Not Found Status with message and boolean success details(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/07Batch_delete.feature:35)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.226"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.271"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.251"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.280"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.474"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.225"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.269"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.204"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.267"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.221"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="3.513"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.251"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.243"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.318"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.259"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.266"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.203"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.295"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="4.167"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.209"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.226"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.287">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.StepDefinition.UserControllerStepDef.admin_receives_with_response_body_for_updated_user(UserControllerStepDef.java:572)
at ✽.Admin receives "400" with response body for Updated user.(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/05UserModule_PUT.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.220"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.237"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="3.194"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.208"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.203"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.240"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.320"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.391"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.236"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.307"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.264"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.587">
    <failure message="expected [400] but found [201]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [201]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.StepDefinition.UserControllerStepDef.admin_receives_with_response_body(UserControllerStepDef.java:105)
at ✽.Admin receives "400" with response body.(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/04UserModule_POST_GET.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.622">
    <failure message="expected [400] but found [201]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [201]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.StepDefinition.UserControllerStepDef.admin_receives_with_response_body(UserControllerStepDef.java:105)
at ✽.Admin receives "400" with response body.(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/04UserModule_POST_GET.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.301"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.232"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.222"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.271"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.505"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.252"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.269"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.365"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.252"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.216"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.219"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.504"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="1.388"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.269"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.329"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="3.910"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.230"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.362"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.304"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.439"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.268"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.239"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="2.243"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.254"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.248"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.271"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.232"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.235"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.289"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.268">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.StepDefinition.UserControllerStepDef.admin_receives_with_response_body_for_updated_user(UserControllerStepDef.java:572)
at ✽.Admin receives "400" with response body for Updated user.(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/05UserModule_PUT.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.253"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.294"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.281"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.252"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.268"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.410"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.204"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.219"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.375"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.227"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.253"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.298"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.213"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.253">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.StepDefinition.UserControllerStepDef.admin_receives_with_response_body_for_updated_user(UserControllerStepDef.java:572)
at ✽.Admin receives "400" with response body for Updated user.(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/05UserModule_PUT.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.236"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.235"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.257"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.364"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.211"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.262">
    <failure message="expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at org.testng.Assert.assertEquals(Assert.java:1429)
at api.StepDefinition.UserControllerStepDef.admin_receives_with_response_body_for_updated_user(UserControllerStepDef.java:572)
at ✽.Admin receives "400" with response body for Updated user.(file:///C:/Users/DELL/git/Team7_APICoders/src/test/resources/Features/05UserModule_PUT.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.267"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.429"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.254"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.286"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.269"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.472"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.275"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.255"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.422"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.284"/>
  <testcase classname="api.TestRunner.TestRunner" name="runScenario" time="0.233"/>
</testsuite> <!-- api.TestRunner.TestRunner -->
